M48
; DRILL file KiCad 10.0.5 date 2026-08-11T15:09:31
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-08-11T15:09:31-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X4.7181Y-3.9528
X4.7181Y-4.1811
T2
X4.7736Y-4.6
X4.9508Y-4.6
M30
